set encoding=utf-8
set fileencodings=utf-8,cp950
set nocompatible 
set number 
set ruler        
set backspace=2  
set ic           
set ru           
set hlsearch     
set incsearch    
set smartindent  
set confirm      
set history=100  
set cursorline
set tabstop=8
set expandtab
set shiftwidth=4
set softtabstop=4
set background=dark
let Tlist_Ctags_Cmd="/usr/local/bin/ctags"
set laststatus=2
